Add partner fee meta-data
cowprotocol/app-data pull request #53
Opened 2024-02-15 16:57 UTC by anxolin

2024-02-15 16:59 UTC, anxolin commented on README.md
> +  - For example: https://github.com/cowprotocol/app-data/pull/44/commits/aeef8a58e7bbd2a53664ce396011cb157a18406d
unrelated: this link was just broken

2024-02-15 17:21 UTC, alfetopito requested changes
Other than the comments, the build is currently broken

2024-02-15 18:03 UTC, anxolin commented
The build was broken before. Fixing in https://github.com/cowprotocol/app-data/pull/54

2024-02-15 18:35 UTC, anxolin commented on src/schemas/definitions.json
> +      "$id": "#/definitions/bips",
I did the other way around here: https://github.com/cowprotocol/app-data/pull/55

2024-02-15 18:37 UTC, anxolin commented on src/scripts/compile.ts
> +export const LATEST_PARTNER_FEE_METADATA_VERSION = '${extractSemver(latestWidgetVersion)}'
Fixed 0d13cb8f7ad8614e982034371b5f70b8328df72a

2024-02-16 10:38 UTC, alfetopito commented on test/schema.spec.ts
> +describe('Schema v0.12.0', () => {
As mentioned in #55, v0.12 won't be created. It'll be v1.0 instead

2024-02-19 14:28 UTC, fleupold commented
Can we call it bps. Bips is very colloquial and not the official abbreviation: https://www.investopedia.com/ask/answers/what-basis-point-bps

2024-02-19 18:10 UTC, anxolin commented
@fleupold no problem with that on my end. The only issue will be that for coherence would be great if I change it also in the quote information. I could make it part of the breaking change https://github.com/cowprotocol/app-data/pull/55 

This would require @olgafetisova to adapt the queries, and I'm unsure if that's problematic or not. Maybe she could confirm if it's ok to rename.

2024-02-19 18:15 UTC, alfetopito commented
> @fleupold no problem with that on my end. The only issue will be that for coherence would be great if I change it also in the quote information. I could make it part of the breaking change #55
> 
> This would require @olgafetisova to adapt the queries, and I'm unsure if that's problematic or not. Maybe she could confirm if it's ok to rename.

Keep in mind this change would require analytics to handle both cases for `quotes`

2024-02-19 18:20 UTC, anxolin commented
> Keep in mind this change would require analytics to handle both cases for quotes

yes, that was my point. This is why I bring it up:

- Option 1: keep all as defined in #53 and #54 (coherent, using the colloquial term)
- Option 2: use bps in `parnerFee` but not in `quote`  (incoherent, using the right term at least in the partner fee)
- Option 3: use bps in both `parnerFee` and quote `quote` (coherent, using the right term, potentially adding trouble for analytics to adapt queries or discard older data in some queries)

2024-02-19 18:44 UTC, anxolin commented on test/schema.spec.ts
> +describe('Schema v0.12.0', () => {
Okay, but the changes are independent and I did the version here. I thought is ok to version it still, as those are 2 different changes and the one in this PR is backward compatible

I will delete the 0.12.0 in #54 instead as it seems you prefer 0.12.0 don't exist. If fine with that

2024-02-19 18:48 UTC, anxolin commented on test/schema.spec.ts
> +describe('Schema v0.12.0', () => {
a4789f02b2c2e7a852ee52febacb1e2368c45428

2024-02-20 02:05 UTC, olgafetisova commented
> This would require @olgafetisova to adapt the queries, and I'm unsure if that's problematic or not. Maybe she could confirm if it's ok to rename.

We are currently changing slippageBips to integer in the [code](https://github.com/duneanalytics/spellbook/blob/788bf984c292f9311dc0394ff6f97dfe5f6f8cec/models/cow_protocol/ethereum/cow_protocol_ethereum_app_data.sql#L43) right away before doing any other adjustments, so I think casting both string and integer to integer should not break anything.

2024-02-20 08:58 UTC, alfetopito commented
> > Keep in mind this change would require analytics to handle both cases for quotes
> 
> yes, that was my point. This is why I bring it up:
> 
>     * Option 1: keep all as defined in [Add partner fee meta-data #53](https://github.com/cowprotocol/app-data/pull/53) and [Fix build #54](https://github.com/cowprotocol/app-data/pull/54) (coherent, using the colloquial term)
> 
>     * Option 2: use bps in `parnerFee` but not in `quote`  (incoherent, using the right term at least in the partner fee)
> 
>     * Option 3: use bps in both `parnerFee` and quote `quote` (coherent, using the right term, potentially adding trouble for analytics to adapt queries or discard older data in some queries)

Due to historical reasons and consistency, I prefer `option 1`.
Unless @olgafetisova doesn't mind the additional change/handling to go for `option 3`

2024-02-20 11:19 UTC, olgafetisova commented
> > ```
> > * Option 1: keep all as defined in [Add partner fee meta-data #53](https://github.com/cowprotocol/app-data/pull/53) and [Fix build #54](https://github.com/cowprotocol/app-data/pull/54) (coherent, using the colloquial term)
> > 
> > * Option 2: use bps in `parnerFee` but not in `quote`  (incoherent, using the right term at least in the partner fee)
> > 
> > * Option 3: use bps in both `parnerFee` and quote `quote` (coherent, using the right term, potentially adding trouble for analytics to adapt queries or discard older data in some queries)
> > ```

If you change slippageBips to bips then it will break some queries, not a big work to adjust it but might take 1-3 days from Dune side to approve the PR, so we might be experiencing some issues there. So I would prefer the name to stay as it is for slippage. 

If you change slippageBips from string to integer, it won't break the code. Everything will remain as is.

2024-02-20 13:33 UTC, anxolin commented
I would personally not add you 1-3 days of work for this name change (discard option 3) @fleupold do you agree? 

If we can't change it for the quote, I would slightly prefer option 2, yes it's not coherent but at least we don't keep using the wrong term for some metadata that is more relevant for integrators. 

Otherwise, we can go with option 1.

2024-02-21 17:05 UTC, olgafetisova commented
I went over the documentation again and  I do not see any simple way to allow a non-existing column in the code (as it will happen when we add the change). The change has to happen on the ETL side which is written in a flat way (same as in our backend), hence, there is no consideration for columns.
To conclude, my strong preference would be to keep the name as is as I did not find an easy way to adjust the code.

2024-02-22 19:23 UTC, anxolin commented
Okay, I believe we arrive to consensus over option 2. I applied the changes. Will create a release of this library

2024-02-22 19:25 UTC, merged

2024-02-23 11:55 UTC, alfetopito reviewed
👍